services:
  gupt-bots:
    build: .
    image: gupt-bots
    container_name: gupt-bots
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      PORT: "8080"
    restart: unless-stopped
